### ISSUE TITLE
Stuck on "processing database" - database not created

### ISSUE THREAD

**Issue by pauline-ng** [pauline-ng/SIFT4G_Create_Genomic_DB#2] opened 2017-05-12 08:32 UTC
Copy/pasted from a SIFT user, using a MAC:

After a while it exists without creating the database with the following command:

** Checking query data and substitutions files **
* processing queries: 100.00/100.00% *

** Searching database for candidate sequences **
* processing database part 157 (size ~0.25 GB): 85.00/100.00% **

And I realized that the homo sapiens small test file also runs until this step and stops without an error or warning and the database is not created either. It is my bad that I never checked the database created for the test files and assumed that it was ok as no error messages were printed.

I am thinking this could be due to RAM limitations. I am currently running this on my local computer (16 GB RAM). Do you think that would be the problem? I also tried installing this on our computing cluster, but sift4g is giving errors. Those are I think related to compiler version issues but I am using the version recommended (4.8). The error message (following) points to compiler version which according to stackoverflow can be fixed by compiling with 4.9. So I will try that. 

** Checking query data and substitutions files **
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted

**Comment by melisakman** [comment] 2017-08-08 00:09
Compiling with gcc 4.9 solved the regex_error issue. I started running local database construction on our computing cluster by requesting more RAM for homo_sapiens_small. It still fails with no error message created. The last line is:
** Searching database for candidate sequences **
* processing database part 108 (size ~0.25 GB): 100.00/100.00% *

**Comment by pauline-ng** [comment] 2017-08-08 08:29
Emailed Robert Vaser, author of the SIFT 4G algorthim.
https://github.com/rvaser/sift4g

**Comment by rvaser** [comment] 2017-08-08 10:03
Hello,
could you please provide the command line and corresponding file sizes which yield your error? Does the program freeze or does it end with some error message? Also, what amount of RAM is on your machine.

Best regards,
Robert

**Comment by melisakman** [comment] 2017-08-08 18:35
Hi Robert,
I am using Pauline's test set (homo_sapiens_small; all files are smaller than 50 M). I am running the following command line on our computing cluster with 96 GB of RAM, so I doubt that is the problem.

'perl ./make-SIFT-db-all.pl -config ./test_files/homo_sapiens-test.txt'

The program fails with "error code 255". I ran in debug mode (srun -vvv perl ...) to see if I can get more from it. And these are the last few lines:

processing database part 108 (size ~0.25 GB): 100.00/100.00% *
srun: debug2: Called _write_line
srun: debug2: Leaving _file_write
srun: debug2: Called _file_readable
srun: debug2: Called _file_writable
srun: debug2: Called _file_writable
srun: debug2: Called _file_readable
srun: debug2: Called _file_writable
srun: debug2: Called _file_writable
srun: debug2: Called _file_readable
srun: debug2: Called _file_writable
srun: debug2: Called _file_writable
srun: debug2: got message connection from 10.17.8.19:47533 12
srun: debug2: received task exit
srun: Received task exit notification for 1 task (status=0xff00).
srun: error: bigmem1: task 0: Exited with exit code 255
srun: debug: task 0 done
srun: debug2: false, shutdown
srun: debug2: false, shutdown
srun: debug2: Called _file_readable
srun: debug2: Called _file_writable
srun: debug2: Called _file_writable
srun: debug2: false, shutdown
srun: debug: IO thread exiting
Any advice on fixing the problem is appreciated! Thanks!
My best,
Melis

**Comment by rvaser** [comment] 2017-08-10 14:37
Hi Melis,
could you please run sift4g manually with the small human dataset and report back with your error? The perl script probably suppressed the actual error (exit code 255 is from exit(-1) inside the script). The sift4g command is './sift4g -d <database in FASTA format> -q <queries in FASTA format> --subst <substitution directory> --out <out directory> --sub-results'. You can also try and run it on a smaller database and/or query set.

Best regards,
Robert

**Comment by melisakman** [comment] 2017-08-10 17:00
Hi Robert,
Thanks for your help. Before I ran sift4g with the test files provided on:
https://github.com/rvaser/sift4g/tree/master/test_files <https://github.com/rvaser/sift4g/tree/master/test_files>
This did not give me any error and produced the files. So sift4g is running fine I think. It is the db creation that is failing. I do not have a subst file because I would like to annotate from vcf files directly. And I need to construct a database with my non-model organism. I wonder if there is a way to run the database construction manually without using the perl script.
Best,
Melis

**Comment by rvaser** [comment] 2017-08-10 17:15
Hi Melis,
are you sure that sift4g finishes successfully on homo_sapiens_small? Can you locate the output files? For questions about database construction, @pauline-ng should be able to help you (I am not familiar with that topic).

Best  regards,
Robert

**Comment by melisakman** [comment] 2017-08-10 17:57
Hi Robert,
Sorry I have not been very clear. I ran sift4g with using the test files you provided on your github rep by using the command:

'./bin/sift4g -q ./test_files/query.fasta --subst ./test_files/ -d ./test_files/sample_protein_database.fa'

That works fine and creates the files it should:
LACI_ECOLI.SIFTprediction and PURR_SALTY.SIFTprediction

So I do not think there is a problem with sift4g (except for compiling with gcc 4.8- as mentioned on your github rep- did not work, but compiling with 4.9 solved the issue). 

Then I try to create a database with the script Pauline provided- which also uses sift4g- and that unfortunately fails. I cannot run sift4g on homo_spiens_small because it does not have the subst files. Those homo_sapiens_small test files are for testing database construction. I will try to test it with smaller file sizes to see if RAM is an issue. 

Best,
Melis

**Comment by melisakman** [comment] 2017-08-10 20:26
actually looking a bit more in detail, it looks like the subst files are created fine ad it is stuck in the sift4g step. Now I am running it manually with the code that failed:

‘./bin/sift4g -d ./uniref90.fasta -q ./scripts_to_build_SIFT_db/test_files/homo_sapiens_small//all_prot.fasta --subst ./scripts_to_build_SIFT_db/test_files/homo_sapiens_small//subst --out ./scripts_to_build_SIFT_db/test_files/homo_sapiens_small//SIFT_predictions --sub-results’

I will inform you on the error messages when it is done/fails.

My best,
Melis

**Comment by melisakman** [comment] 2017-08-14 17:31
Hi Robert,

Running the mentioned command it failed at exactly the same process producing the error message:

'/var/spool/slurmd/job13743478/slurm_script: line 18: 35916 Illegal instruction     (core dumped) ./bin/sift4g -d ./uniref90.fasta -q ./scripts_to_build_SIFT_db/test_files/homo_sapiens_small//all_prot.fasta --subst ./scripts_to_build_SIFT_db/test_files/homo_sapiens_small//subst --out ./scripts_to_build_SIFT_db/test_files/homo_sapiens_small//SIFT_predictions --sub-results'

Any suggestions?
Thanks a lot,
Melis

**Comment by rvaser** [comment] 2017-08-15 06:44
Hi Melis,
did you run the homo_sapiens_small on the same machine as the test files provided on sift4g repository? The error might indicate that you compiled the sift4g executable on one machine and uses it on another which does not support the same SIMD/CUDA instruction sets. If this is the case, compile sift4g from source on the new machine and rerun it.

Best regards,
Robert

**Comment by melisakman** [comment] 2017-08-15 18:20
Hi Robert,

Yes, that solved the problem. I complied sift4g on my home folder on our cluster and then run it on a different node assigned by slurm. Now I am compiling sift4g within the same slurm script and it solves the problem. Thank you so much for all the help!

My best,
Melis

**Comment by rvaser** [comment] 2017-08-15 18:32
Hi Melis,
I am glad it worked out. If you don't mind, I shall close this issue.

Best regards,
Robert

**Closed by rvaser** 2017-08-15 18:32 UTC
